### ISSUE TITLE
replace latlong with latlong2?

### ISSUE THREAD

**Issue by tomquas** [Xennis/flutter_map_location#36]
hi, thanks for this great library. i had to replace latlong with latlong2 ~~in order to make it work together with flutter_map. they switched lately in their branch 'issues/829-nullsafety... maybe this is something you want to migrate, too?~~

nope, not that easy... feel free to delete this issue.

**Comment by Xennis** [comment]
Dear @tomquas thanks for reporting. [flutter_map switched to latlong2](https://github.com/fleaflet/flutter_map/pull/854) but they do not released a new version with that change. Once that happened we can update the library here as well and release a new version.

**Comment by tomquas** [comment]
@Xennis awesome, am looking forward to it

**Comment by Xennis** [comment]
Dear @tomquas see #37 I've created a `dev` branch and merged the changes into that. (Once flutter_map releases a new version I'll merge that into the master branch).
