### ISSUE TITLE
update loacaton to suport location 4.x

### ISSUE THREAD

**Issue by mghase** [Xennis/flutter_map_location#39]
flutter_map_location ^0.7.1+1 which depends on location ^3.2.4, location ^3.2.4 is required.
 location ^4.1.1, version solving failed.

**Comment by Xennis** [comment]
Dear @mghase what is napa? Can you please reference that module? I can't find it on https://pub.dev/.

**Comment by Xennis** [comment]
Dear @mghase further on: What do you mean with "support location 4.x"? The module here does support that:

https://github.com/Xennis/flutter_map_location/blob/e9afc03d3351da87ffc01d6e27922b9d1e62fbed/pubspec.yaml#L16

That's the latest version https://pub.dev/packages/location/versions .

**Comment by Xennis** [comment]
Close it because there was no further comments. Use the latest version to get support for the latest `location` version.
