### ISSUE TITLE
How can i unsubscribed location?

### ISSUE THREAD

**Issue by mtan11** [Xennis/flutter_map_location#52]
I want build a button first click subscribe location and after that is unsubscribed? I can't find an example for this case. Please let me know i can do this?

**Comment by Xennis** [comment]
Hey @mtan11 can you explain the case in more detail? You want to unsubscribe from location updates on a button click?

**Comment by mtan11** [comment]
Yes, that all i need. Can i choose to get or not get user location in the first time?

**Comment by Xennis** [comment]
Hi. #38 was just merged. With that change you can. There is no option to unsubscribe.

**Comment by mtan11** [comment]
Thanks for your help

**Comment by Xennis** [comment]
#76 adds basic support to unsubscribe via a controller.
