### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [Xennis/flutter_map_location#63]
Would be great to have null safety integrated now as `flutter_map` published their null-safety code.

**Comment by Xennis** [comment]
Yeah :tada: The [dev](https://github.com/Xennis/flutter_map_location/tree/dev) already has null safety. It was added in #34 . If flutter_map has now released a new version we can merge that into the master.

**Comment by TheOneWithTheBraid** [comment]
Yes, the `flutter_map` upstream bug mentioned in #64 is now fixed too it would be great to have this published soonly because currently, the pub.dev-version became incompstible with flutter_map.

**Comment by Xennis** [comment]
Sure. First steps are taken:

* Update dev branch to that version #65
* Merge dev branch will all the nice futures into master #66 :tada: 

Open: Write proper release notes and publish.

**Comment by Xennis** [comment]
Prepared a new release in #68  . Now it's published https://pub.dev/packages/flutter_map_location/changelog
