### ISSUE TITLE
toggle location on/off

### ISSUE THREAD

**Issue by MichalNemec** [Xennis/flutter_map_location#69]
Hello, is it possible somehow to have toggle controls for location fab button?
if clicked -> show location marker and follow
if clicked again -> hide location marker and not follow

Thanks!

**Comment by Xennis** [comment]
Dear @MichalNemec not sure if that's in scope of the plugin here. Can you describe your use case a little bit more detailed? Regards, Xennis

**Comment by MichalNemec** [comment]
@Xennis im using flutter map to display markers depending on my POI. I want to see all markers with fitbounds (upon load, i want to see every marker available).
When i click on location fab button, i want to see where i am currently positioned. When i want to see all of the markers again, then i can click fab button to "disable" location.

Basically:
- state overview - show all markers without my location
- state location - show my location in center (user cares about nearest marker, dont care about all of them)

Hopefuly i explained it and its more clear.

current state i have is:
- state overview - showing all markers without my location - done
- state location - show my location in center - done (but when i click the btn again, its not toggling off the marker and location fetch)

**Comment by Xennis** [comment]
Thanks for the explanation. Currently it's not supported to unsubscribe from the location updates. An idea could be to provide a controller that can be used outside of the plugin to unsubscribe (and also other actions like subscribing).

That on the second click the unsubscribe happens is nothing I see within the plugin. Instead something that can be build with that exposed controller.

**Comment by MichalNemec** [comment]
exposed controller would be really nice _FMLController.listen() _FMLController.dispose would suffice

**Comment by Xennis** [comment]
Started working on it. See #74

**Comment by Xennis** [comment]
Dear @MichalNemec a first simple version of a controller that can be used to unsubscribe was merged in #76 . I've added a new page in the example.

**Comment by Xennis** [comment]
There were no further comments. Close the issue.
