### ISSUE TITLE
Default app broken

### ISSUE THREAD

**Issue by asimbo** [Xennis/flutter_map_location#72]
Hie, I am trying to run the plugin using the default page app as coded in your example. However am failing to reproduce it and show live tracking of location. Has the coded being change such that the example has been left broken>

**Comment by Xennis** [comment]
Dear @asimbo what kind of error message to get in the logs? What version do the plugin to you us (if you use an unreleased version let me please know which Git hash you use)?

**Comment by Xennis** [comment]
I've tried to run the example from the latest master and it worked. So I'm waiting for the request information above. Let's see if we then find the issue.

**Comment by asimbo** [comment]
I have downloaded the example app from github. I can confirm its working fine. Am just failing to get to work with in my app. The only difference from my code is I am using the topography open tile and am import the flutter_map lib as a dependency.

**Comment by dariocavada** [comment]
What's the url of the github example ?

**Comment by asimbo** [comment]
https://github.com/Xennis/flutter_map_location this is working fine. I should be an issue with an older version of flutter_map. Now using the latest. All is well. Thanx
