### ISSUE TITLE
Add options to set the GPS accuracy

### ISSUE THREAD

**Issue by SeCo89** [Xennis/flutter_map_location#78]
Hey there,

is it possible to modify the accuracy of the GPS location like so:
https://stackoverflow.com/questions/64714745/flutter-how-to-get-my-location-high-accuracy

I couldn't find the correct way of doing it with this plugin.

Thanks in advance!

**Comment by Xennis** [comment]
Hey @SeCo89 that's not possible yet. Only the `intervalDuration` can be set as plugin option. Are you interested in create a PR for that?

**Comment by SeCo89** [comment]
I created a PR: 
https://github.com/Xennis/flutter_map_location/pull/79

Greetings

**Comment by Xennis** [comment]
The PR is merged.
